version: '3'

services: 

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - node

  node:
    build:
      context: ./node
    container_name: node
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes: 
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=myapp

networks: 
  node-network:
    driver: bridge      
